name: wazo-chanspy
namespace: quintana
version: 0.0.1
author: Sylvain Boily
display_name: Chan spy extension
min_wazo_version: 23.08
tags:
  - experimental
homepage: https://github.com/sboily/wazo-chanspy
